# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - config/puma.rb
    - tmp/**/*
    - db/schema.rb

FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Exclude:
    - spec/**/*_spec.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/BlockLength:
  Exclude:
    - db/schema.rb

Metrics/ModuleLength:
  Exclude:
    - db/seeds.rb

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - given

RSpec/NestedGroups:
  Max: 4

RSpec/Rails/InferredSpecType:
  Enabled: false

Style/Documentation:
  Exclude:
    - app/helpers/application_helper.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - config/application.rb
    - db/migrate/*.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - db/seeds.rb
